### ISSUE TITLE
Cannot find module 'nestjs-meilisearch' or its corresponding type declarations.

### ISSUE THREAD

**Issue by jonitiso** [lambrohan/nestjs-meilisearch#14] opened 2024-10-22 16:31 UTC
Works with "nestjs-meilisearch": "2.1.6",

Fail with "nestjs-meilisearch": "2.1.7",

src/search/search.service.ts:3:35 - error TS2307: Cannot find module 'nestjs-meilisearch' or its corresponding type declarations.

import { InjectMeiliSearch } from 'nestjs-meilisearch';

**Comment by kylejb** [comment] 2024-10-22 17:00
FYI – this is a duplicate of https://github.com/lambrohan/nestjs-meilisearch/issues/13

**Comment by lambrohan** [comment] 2024-10-22 17:16
sorry for careless release guys, should be ok now!
https://www.npmjs.com/package/nestjs-meilisearch/v/2.1.8

**Closed as completed by lambrohan** 2024-10-22 17:16 UTC

**Comment by kylejb** [comment] 2024-10-22 17:18
No worries – it happens! Teamwork :)
